// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Req / Resp
type GetAllUserReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUserReq) Reset()         { *m = GetAllUserReq{} }
func (m *GetAllUserReq) String() string { return proto.CompactTextString(m) }
func (*GetAllUserReq) ProtoMessage()    {}
func (*GetAllUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{0}
}

func (m *GetAllUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserReq.Unmarshal(m, b)
}
func (m *GetAllUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserReq.Marshal(b, m, deterministic)
}
func (m *GetAllUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserReq.Merge(m, src)
}
func (m *GetAllUserReq) XXX_Size() int {
	return xxx_messageInfo_GetAllUserReq.Size(m)
}
func (m *GetAllUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserReq proto.InternalMessageInfo

type GetAllUserResp struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUserResp) Reset()         { *m = GetAllUserResp{} }
func (m *GetAllUserResp) String() string { return proto.CompactTextString(m) }
func (*GetAllUserResp) ProtoMessage()    {}
func (*GetAllUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{1}
}

func (m *GetAllUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserResp.Unmarshal(m, b)
}
func (m *GetAllUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserResp.Marshal(b, m, deterministic)
}
func (m *GetAllUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserResp.Merge(m, src)
}
func (m *GetAllUserResp) XXX_Size() int {
	return xxx_messageInfo_GetAllUserResp.Size(m)
}
func (m *GetAllUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserResp proto.InternalMessageInfo

func (m *GetAllUserResp) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type CreateGuestUserReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGuestUserReq) Reset()         { *m = CreateGuestUserReq{} }
func (m *CreateGuestUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateGuestUserReq) ProtoMessage()    {}
func (*CreateGuestUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{2}
}

func (m *CreateGuestUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGuestUserReq.Unmarshal(m, b)
}
func (m *CreateGuestUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGuestUserReq.Marshal(b, m, deterministic)
}
func (m *CreateGuestUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGuestUserReq.Merge(m, src)
}
func (m *CreateGuestUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateGuestUserReq.Size(m)
}
func (m *CreateGuestUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGuestUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGuestUserReq proto.InternalMessageInfo

func (m *CreateGuestUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateGuestUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateGuestUserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGuestUserResp) Reset()         { *m = CreateGuestUserResp{} }
func (m *CreateGuestUserResp) String() string { return proto.CompactTextString(m) }
func (*CreateGuestUserResp) ProtoMessage()    {}
func (*CreateGuestUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{3}
}

func (m *CreateGuestUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGuestUserResp.Unmarshal(m, b)
}
func (m *CreateGuestUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGuestUserResp.Marshal(b, m, deterministic)
}
func (m *CreateGuestUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGuestUserResp.Merge(m, src)
}
func (m *CreateGuestUserResp) XXX_Size() int {
	return xxx_messageInfo_CreateGuestUserResp.Size(m)
}
func (m *CreateGuestUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGuestUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGuestUserResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetAllUserReq)(nil), "gonpe.server.admin_service.GetAllUserReq")
	proto.RegisterType((*GetAllUserResp)(nil), "gonpe.server.admin_service.GetAllUserResp")
	proto.RegisterType((*CreateGuestUserReq)(nil), "gonpe.server.admin_service.CreateGuestUserReq")
	proto.RegisterType((*CreateGuestUserResp)(nil), "gonpe.server.admin_service.CreateGuestUserResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminClient interface {
	GetAllUser(ctx context.Context, in *GetAllUserReq, opts ...grpc.CallOption) (*GetAllUserResp, error)
	CreateGuestUser(ctx context.Context, in *CreateGuestUserReq, opts ...grpc.CallOption) (*CreateGuestUserResp, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GetAllUser(ctx context.Context, in *GetAllUserReq, opts ...grpc.CallOption) (*GetAllUserResp, error) {
	out := new(GetAllUserResp)
	err := c.cc.Invoke(ctx, "/gonpe.server.admin_service.Admin/GetAllUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateGuestUser(ctx context.Context, in *CreateGuestUserReq, opts ...grpc.CallOption) (*CreateGuestUserResp, error) {
	out := new(CreateGuestUserResp)
	err := c.cc.Invoke(ctx, "/gonpe.server.admin_service.Admin/CreateGuestUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
type AdminServer interface {
	GetAllUser(context.Context, *GetAllUserReq) (*GetAllUserResp, error)
	CreateGuestUser(context.Context, *CreateGuestUserReq) (*CreateGuestUserResp, error)
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_GetAllUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAllUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gonpe.server.admin_service.Admin/GetAllUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAllUser(ctx, req.(*GetAllUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateGuestUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGuestUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateGuestUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gonpe.server.admin_service.Admin/CreateGuestUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateGuestUser(ctx, req.(*CreateGuestUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gonpe.server.admin_service.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllUser",
			Handler:    _Admin_GetAllUser_Handler,
		},
		{
			MethodName: "CreateGuestUser",
			Handler:    _Admin_CreateGuestUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_service.proto",
}

func init() { proto.RegisterFile("admin_service.proto", fileDescriptor_f9bc00259dc38d22) }

var fileDescriptor_f9bc00259dc38d22 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x35, 0xa2, 0x23, 0x5a, 0x98, 0x2a, 0x86, 0x3d, 0x95, 0x3d, 0x55, 0xc1, 0x15,
	0xea, 0x03, 0x48, 0x15, 0xec, 0xbd, 0xe0, 0xc5, 0x8b, 0x6c, 0xdb, 0x41, 0x02, 0x69, 0x77, 0x9c,
	0xd9, 0xea, 0xeb, 0xfa, 0x28, 0x92, 0x8d, 0xa8, 0x31, 0x28, 0x7a, 0x9c, 0xd9, 0x6f, 0x7e, 0xfe,
	0x8f, 0x85, 0x81, 0x5f, 0xae, 0xca, 0xf5, 0x83, 0x92, 0x3c, 0x97, 0x0b, 0x72, 0x2c, 0x21, 0x06,
	0x34, 0x8f, 0x61, 0xcd, 0xe4, 0xea, 0x25, 0x89, 0x6b, 0x11, 0x06, 0x36, 0x4a, 0xd2, 0x70, 0xb6,
	0x0f, 0x07, 0x53, 0x8a, 0x93, 0xaa, 0xba, 0x53, 0x92, 0x19, 0x3d, 0xd9, 0x2b, 0x38, 0xfc, 0xba,
	0x50, 0xc6, 0x73, 0xc8, 0xeb, 0x03, 0x2d, 0xb2, 0xe1, 0xd6, 0x68, 0x7f, 0x7c, 0xe2, 0x5a, 0xd1,
	0x29, 0x2b, 0xb1, 0x0d, 0x65, 0x6f, 0x01, 0x6f, 0x84, 0x7c, 0xa4, 0xe9, 0x86, 0x34, 0xbe, 0xc7,
	0xe2, 0x11, 0xe4, 0xb4, 0xf2, 0x65, 0x55, 0x64, 0xc3, 0x6c, 0xb4, 0x37, 0x6b, 0x06, 0x34, 0xb0,
	0xcb, 0x5e, 0xf5, 0x25, 0xc8, 0xb2, 0xe8, 0xa5, 0x87, 0x8f, 0xd9, 0x1e, 0xc3, 0xa0, 0x93, 0xa3,
	0x3c, 0x7e, 0xcd, 0x20, 0x9f, 0xd4, 0x3a, 0xb8, 0x00, 0xf8, 0x6c, 0x8a, 0xa7, 0xee, 0x67, 0x63,
	0xd7, 0x52, 0x34, 0x67, 0x7f, 0x45, 0x95, 0x51, 0xa0, 0xff, 0xad, 0x05, 0xba, 0xdf, 0xce, 0xbb,
	0xea, 0xe6, 0xe2, 0x5f, 0xbc, 0xf2, 0xf5, 0xf6, 0x7d, 0x8f, 0xe7, 0xf3, 0x9d, 0xf4, 0x41, 0x97,
	0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x58, 0x39, 0xef, 0xc2, 0xdf, 0x01, 0x00, 0x00,
}
