// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User_Role int32

const (
	User_ROLE_GUEST  User_Role = 0
	User_ROLE_VIEWER User_Role = 1
	User_ROLE_ADMIN  User_Role = 2
)

var User_Role_name = map[int32]string{
	0: "ROLE_GUEST",
	1: "ROLE_VIEWER",
	2: "ROLE_ADMIN",
}

var User_Role_value = map[string]int32{
	"ROLE_GUEST":  0,
	"ROLE_VIEWER": 1,
	"ROLE_ADMIN":  2,
}

func (x User_Role) String() string {
	return proto.EnumName(User_Role_name, int32(x))
}

func (User_Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0, 0}
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role                 User_Role            `protobuf:"varint,2,opt,name=role,proto3,enum=gonpe.server.user.User_Role" json:"role,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetRole() User_Role {
	if m != nil {
		return m.Role
	}
	return User_ROLE_GUEST
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("gonpe.server.user.User_Role", User_Role_name, User_Role_value)
	proto.RegisterType((*User)(nil), "gonpe.server.user.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0x47, 0xcd, 0xba, 0x15, 0x3a, 0x85, 0x18, 0x17, 0x0f, 0xa1, 0x08, 0x86, 0x9e, 0x72, 0x9a,
	0x4a, 0x3d, 0x88, 0xc7, 0x88, 0x41, 0x0a, 0xfe, 0x81, 0xb5, 0x55, 0xf0, 0x52, 0x12, 0x33, 0x86,
	0x40, 0xe2, 0x2e, 0x9b, 0x8d, 0xdf, 0xc2, 0xef, 0x2c, 0xd9, 0x34, 0x5e, 0x3c, 0x78, 0x1c, 0xe6,
	0xbd, 0x1f, 0x0f, 0xa0, 0x6b, 0xc9, 0xa0, 0x36, 0xca, 0x2a, 0x71, 0x52, 0xaa, 0x4f, 0x4d, 0xd8,
	0x92, 0xf9, 0x22, 0x83, 0xfd, 0x63, 0x7e, 0x5e, 0x2a, 0x55, 0xd6, 0xb4, 0x74, 0x40, 0xde, 0x7d,
	0x2c, 0x6d, 0xd5, 0x50, 0x6b, 0xb3, 0x46, 0x0f, 0xce, 0xe2, 0x9b, 0x01, 0xdf, 0xb6, 0x64, 0x84,
	0x0f, 0xac, 0x2a, 0x42, 0x2f, 0xf2, 0xe2, 0xa9, 0x64, 0x55, 0x21, 0x2e, 0x80, 0x1b, 0x55, 0x53,
	0xc8, 0x22, 0x2f, 0xf6, 0x57, 0x67, 0xf8, 0x67, 0x1b, 0x7b, 0x0d, 0xa5, 0xaa, 0x49, 0x3a, 0x52,
	0x9c, 0xc2, 0x84, 0x9a, 0xac, 0xaa, 0xc3, 0x43, 0x37, 0x32, 0x1c, 0xe2, 0x1a, 0xe0, 0xdd, 0x50,
	0x66, 0xa9, 0xd8, 0x65, 0x36, 0xe4, 0x91, 0x17, 0xcf, 0x56, 0x73, 0x1c, 0xb2, 0x70, 0xcc, 0xc2,
	0xcd, 0x98, 0x25, 0xa7, 0x7b, 0x3a, 0xb1, 0xbd, 0xda, 0xe9, 0x62, 0x54, 0x27, 0xff, 0xab, 0x7b,
	0x3a, 0xb1, 0x8b, 0x2b, 0xe0, 0x7d, 0x99, 0xf0, 0x01, 0xe4, 0xd3, 0x7d, 0xba, 0xbb, 0xdb, 0xa6,
	0xcf, 0x9b, 0xe0, 0x40, 0x1c, 0xc3, 0xcc, 0xdd, 0x2f, 0xeb, 0xf4, 0x35, 0x95, 0x81, 0xf7, 0x0b,
	0x24, 0xb7, 0x0f, 0xeb, 0xc7, 0x80, 0xdd, 0xf0, 0x37, 0xa6, 0xf3, 0xfc, 0xc8, 0xad, 0x5f, 0xfe,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x53, 0xfd, 0xa3, 0xef, 0x5e, 0x01, 0x00, 0x00,
}
